version: '3.5'
services:

  frontend-microservice:
    image: github.com/mkadiri/frontend-microservice:local
    container_name: frontend-microservice
    environment:
      - VIRTUAL_HOST=frontend-microservice.local.syrupme.net
      - VIRTUAL_PORT=4200
    volumes:
      - ./app:/app
    ports:
      - 4200:4200

networks:
  default:
    external:
      name: auto